AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Simulated pre-existing infrastructure — Lambda with CloudWatch Alarm for errors

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 128

Resources:
  MockDispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mock-lambda-dispatcher
      Handler: lambda_mock.dispatcher.handler
      CodeUri: .
      Timeout: 1
      Description: Mock Lambda with intentional bugs (div-by-zero, type error, timeout)

  MockDispatcherErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: mock-lambda-errors
      AlarmDescription: !Sub "LogGroup=/aws/lambda/${MockDispatcherFunction}"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref MockDispatcherFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

Outputs:
  MockDispatcherFunctionArn:
    Description: Mock Lambda function ARN
    Value: !GetAtt MockDispatcherFunction.Arn

  MockDispatcherFunctionName:
    Description: Mock Lambda function name
    Value: !Ref MockDispatcherFunction

  MockDispatcherErrorAlarmArn:
    Description: CloudWatch alarm ARN
    Value: !GetAtt MockDispatcherErrorAlarm.Arn
